service: aws-nodejs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1

package:
  exclude:
    - README.md
    - popoulate.sh

functions:
  reset:
    handler: handler.reset
    memorySize: 128
    events:
      - http:
          path: reset
          method: post